[package]
name = "rsst"
version = "0.1.0"
authors = ["c25vdw <lucaszeng99@gmail.com>"]
edition = "2018"

[dependencies]
termios = "0.3.3"
rss = "1.10.0"
reqwest = "0.11.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.38"
thiserror = "1.0"
html2text = "0.2.1"
